//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceHub.WSPublicEHoaDon
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap")]
    public interface WSPublicEHoaDonSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecCommandResponse> ExecCommandAsync(InvoiceHub.WSPublicEHoaDon.ExecCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecuteCommandResponse> ExecuteCommandAsync(InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecCommandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecCommand", Namespace="http://tempuri.org/", Order=0)]
        public InvoiceHub.WSPublicEHoaDon.ExecCommandRequestBody Body;
        
        public ExecCommandRequest()
        {
        }
        
        public ExecCommandRequest(InvoiceHub.WSPublicEHoaDon.ExecCommandRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecCommandRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CommandData;
        
        public ExecCommandRequestBody()
        {
        }
        
        public ExecCommandRequestBody(string partnerGUID, string CommandData)
        {
            this.partnerGUID = partnerGUID;
            this.CommandData = CommandData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecCommandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecCommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public InvoiceHub.WSPublicEHoaDon.ExecCommandResponseBody Body;
        
        public ExecCommandResponse()
        {
        }
        
        public ExecCommandResponse(InvoiceHub.WSPublicEHoaDon.ExecCommandResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecCommandResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecCommandResult;
        
        public ExecCommandResponseBody()
        {
        }
        
        public ExecCommandResponseBody(string ExecCommandResult)
        {
            this.ExecCommandResult = ExecCommandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteCommandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteCommand", Namespace="http://tempuri.org/", Order=0)]
        public InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequestBody Body;
        
        public ExecuteCommandRequest()
        {
        }
        
        public ExecuteCommandRequest(InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteCommandRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartnerGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EncryptedCommandData;
        
        public ExecuteCommandRequestBody()
        {
        }
        
        public ExecuteCommandRequestBody(string PartnerGUID, string EncryptedCommandData)
        {
            this.PartnerGUID = PartnerGUID;
            this.EncryptedCommandData = EncryptedCommandData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteCommandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteCommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public InvoiceHub.WSPublicEHoaDon.ExecuteCommandResponseBody Body;
        
        public ExecuteCommandResponse()
        {
        }
        
        public ExecuteCommandResponse(InvoiceHub.WSPublicEHoaDon.ExecuteCommandResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteCommandResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteCommandResult;
        
        public ExecuteCommandResponseBody()
        {
        }
        
        public ExecuteCommandResponseBody(string ExecuteCommandResult)
        {
            this.ExecuteCommandResult = ExecuteCommandResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WSPublicEHoaDonSoapChannel : InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WSPublicEHoaDonSoapClient : System.ServiceModel.ClientBase<InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap>, InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSPublicEHoaDonSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSPublicEHoaDonSoapClient.GetBindingForEndpoint(endpointConfiguration), WSPublicEHoaDonSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPublicEHoaDonSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSPublicEHoaDonSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPublicEHoaDonSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSPublicEHoaDonSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPublicEHoaDonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecCommandResponse> InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap.ExecCommandAsync(InvoiceHub.WSPublicEHoaDon.ExecCommandRequest request)
        {
            return base.Channel.ExecCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecCommandResponse> ExecCommandAsync(string partnerGUID, string CommandData)
        {
            InvoiceHub.WSPublicEHoaDon.ExecCommandRequest inValue = new InvoiceHub.WSPublicEHoaDon.ExecCommandRequest();
            inValue.Body = new InvoiceHub.WSPublicEHoaDon.ExecCommandRequestBody();
            inValue.Body.partnerGUID = partnerGUID;
            inValue.Body.CommandData = CommandData;
            return ((InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap)(this)).ExecCommandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecuteCommandResponse> InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap.ExecuteCommandAsync(InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequest request)
        {
            return base.Channel.ExecuteCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceHub.WSPublicEHoaDon.ExecuteCommandResponse> ExecuteCommandAsync(string PartnerGUID, string EncryptedCommandData)
        {
            InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequest inValue = new InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequest();
            inValue.Body = new InvoiceHub.WSPublicEHoaDon.ExecuteCommandRequestBody();
            inValue.Body.PartnerGUID = PartnerGUID;
            inValue.Body.EncryptedCommandData = EncryptedCommandData;
            return ((InvoiceHub.WSPublicEHoaDon.WSPublicEHoaDonSoap)(this)).ExecuteCommandAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPublicEHoaDonSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSPublicEHoaDonSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPublicEHoaDonSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsdemo.ehoadon.vn/WSPublicEHoaDon.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSPublicEHoaDonSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsdemo.ehoadon.vn/WSPublicEHoaDon.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSPublicEHoaDonSoap,
            
            WSPublicEHoaDonSoap12,
        }
    }
}
